### ISSUE TITLE
OTP Entered Is Not Valid

### ISSUE THREAD

**Issue by 0xabdi** [mosip/mosip-infra#688]
I am running MSOIP Sandbox-v2 v1.1.2 on-premise using self-signed certificates. All the `mz` and `dmz` pods are running properly but when I try to enter the default `OTP` of `111111` in the `pre-registration-ui`. I am getting the below error.

![image](https://user-images.githubusercontent.com/17492419/120472756-92cfa000-c3a6-11eb-857d-d756c0160f95.png)

**Comment by callummole** [comment]
@0xabdi I have previously had errors with the prereg UI even when all pods claim to be running. The errors are either invalid details or logging out due to inactivity. In my experience the fix is restart the pod that is in charge of that particular service. The quickest way to do this is `kc1 delete pods XXXX`, which deletes the pod but not the kubernetes deployment so a new pod is created to house the container. 

I would guess that your error would be fixed by restarting one of the following (can't remember which one exactly):

`ida-otp-service-XXX`
`kernel-otpmanager-service-XXXX`

**Comment by 0xabdi** [comment]
@callummole Let me give it a try. Thanks :)

**Comment by 0xabdi** [comment]
@callummole I restarted both pods with no luck.

**Comment by callummole** [comment]
Try reinstalling the ida helm release?

**Comment by 0xabdi** [comment]
No luck with this too. Reinstalled the `ida` helm release by running `helm1 delete ida` and then `an playbook/ida.yaml`

**Comment by callummole** [comment]
Hmmm. You'll need to hunt down the pod responsible. Unhelpfully the error messages are sometimes only loosely related to the nature of the error. This is a method that I've used successfully in the past to troubleshoot. It may or may not be helpful to you! 

1) Look in the nginx access logs: `sudo tail /var/log/nginx/access.log`. Within the sandbox most things are triggered by API calls. Note the last API call before the error (there often will not be an obvious error code).

2) Look in the nginx config file (`cat /etc/nginx/nginx.conf`) to see whether the api call is routed to `mzworker0.sb` or `dmzworker0.sb`.

3) Look in the relevant ingress resource for the api call. Note the service endpoint. Use:
```
kc1 describe ingress | grep <api identifying string>. 

```

4) The problem is likely to be with the service or the pod of the same name. Try deleting this pod.

5) If this doesn't work, hunt down the helm release and reinstall.

6) If that doesn't work, hold your head in your hands, take a deep breath, and make a coffee.

**Comment by 0xabdi** [comment]
Thanks @callummole for the troubleshooting tips. WIll give them a shot and see how it goes (and I definitely need to make more coffee :)). Funny thing is that I even did a fresh installation with no success. The error still persists.

**Comment by callummole** [comment]
what username are you using? Probably worth double-checking that username and password you are using are valid before going through all the troubleshooting.

**Comment by 0xabdi** [comment]
@callummole the pre-reg-ui only has the option for entering an email address/phone number which the OTP will be sent to. In this case, I was trying to enter my personal email address and the default OTP of 111111. I am not sure if this is the username /password you are talking about.

**Comment by callummole** [comment]
Hmmm, you're right that should work fine.

**Comment by 0xabdi** [comment]
1. Below is the output from `sudo tail /var/log/nginx/access.log`
```
[mosipuser@console ~]$ sudo tail /var/log/nginx/access.log
172.31.76.18 - - [04/Jun/2021:05:33:37 +0000] "GET //preregistration/v1/login/config HTTP/2.0" 200 2329 "https://console.sb/pre-registration-ui/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36" "-"
172.31.76.18 - - [04/Jun/2021:05:33:41 +0000] "GET /pre-registration-ui/5.b1c8f6e21b5a09054bf7.js HTTP/2.0" 200 30950 "https://console.sb/pre-registration-ui/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36" "-"
172.31.76.18 - - [04/Jun/2021:05:33:53 +0000] "GET /pre-registration-ui/common.a4728732ce19b8dbba92.js HTTP/2.0" 200 4441 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36" "-"
172.31.76.18 - - [04/Jun/2021:05:33:59 +0000] "GET /pre-registration-ui/5.b1c8f6e21b5a09054bf7.js HTTP/2.0" 200 30950 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36" "-"
172.31.76.18 - - [04/Jun/2021:05:34:02 +0000] "GET /pre-registration-ui/4.9d271a8b0341194d1905.js HTTP/2.0" 200 229034 "https://console.sb/pre-registration-ui/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36" "-"
172.31.76.18 - - [04/Jun/2021:05:34:20 +0000] "GET /pre-registration-ui/main.3918e424bcfcf385cffe.js HTTP/2.0" 200 1209828 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36" "-"
172.31.76.18 - - [04/Jun/2021:05:34:27 +0000] "GET /pre-registration-ui/4.9d271a8b0341194d1905.js HTTP/2.0" 200 229034 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36" "-"
172.31.76.18 - - [04/Jun/2021:05:34:27 +0000] "POST //preregistration/v1/login/sendOtp HTTP/2.0" 200 211 "https://console.sb/pre-registration-ui/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36" "-"
172.31.76.18 - - [04/Jun/2021:05:34:27 +0000] "POST //preregistration/v1/login/validateOtp HTTP/2.0" 200 213 "https://console.sb/pre-registration-ui/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36" "-"
172.31.76.18 - - [04/Jun/2021:05:34:39 +0000] "GET /pre-registration-ui/3.ed08110376340ae32364.js HTTP/2.0" 200 523156 "https://console.sb/pre-registration-ui/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36" "-"
```
2. The API calls in `/etc/nginx/nginx.conf` are routed to `mzworker0.sb`

**Comment by 0xabdi** [comment]
The default OTP is now working on the pre-reg-ui. I reinstalled the Keycloak helm release by running `helm1 delete keycloak` and `an playbooks/keycloak.yml`. I also realized the system clock on the VMs was not accurate. So, I changed the dates to the correct `UTC` date and time.
